name: select_example
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^4.0.0-beta6
  flutter:
    sdk: flutter

  growerp_select_dialog: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true