name: growerp
repository: https://github.com/growerp/growerp

packages:
  - packages/admin
  - packages/hotel
  - packages/growerp*
  - packages/growerp*/example

ide:
  intellij:
    enabled: false
    
scripts:
  runPubGetInParallel: no
  analyze:
    exec: dart analyze .
  build_all:
    run: dart pub global run melos exec --depends-on="build_runner" "flutter pub run build_runner build --delete-conflicting-outputs"
    description: build_runner build all modules.
  l10n:
    run: dart pub global run melos exec --fail-fast --file-exists="l10n.yaml" flutter gen-l10n
    description: Generates l10n for all app packages.
  