name: growerp
description: growerp system
repository: https://github.com/growerp/growerp

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies: 

dev_dependencies:
  flutter_lints: ^2.0.1
  utils:
    path: packages/utils/
