name: example
description: A example project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  growerp_core:
    path: ../
  growerp_user_company:
    path: ../../growerp_user_company

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cfg/
    - packages/growerp_core/images/about.png
    - packages/growerp_core/images/aboutGrey.png
    - packages/growerp_core/images/accounting.png
    - packages/growerp_core/images/category.png
    - packages/growerp_core/images/categoryGrey.png
    - packages/growerp_core/images/addImage.png
    - packages/growerp_core/images/categories.png
    - packages/growerp_core/images/company.png
    - packages/growerp_core/images/favicon-32x32.png
    - packages/growerp_core/images/growerpPlaystore.png
    - packages/growerp_core/images/orderGrey.png
    - packages/growerp_core/images/supplierGrey.png
    - packages/growerp_core/images/crmGrey.png
    - packages/growerp_core/images/growerp1024x500.jpg
    - packages/growerp_core/images/growerp.png
    - packages/growerp_core/images/order.png
    - packages/growerp_core/images/supplier.png
    - packages/growerp_core/images/accountingGrey.png
    - packages/growerp_core/images/category.png
    - packages/growerp_core/images/crm.png
    - packages/growerp_core/images/growerp50x50.jpg
    - packages/growerp_core/images/infoGrey.png
    - packages/growerp_core/images/personInfo.png
    - packages/growerp_core/images/up-arrow.png
    - packages/growerp_core/images/accounting.png
    - packages/growerp_core/images/chatGrey.png
    - packages/growerp_core/images/dashBoardGrey.png
    - packages/growerp_core/images/growerp512x512.png
    - packages/growerp_core/images/info.png
    - packages/growerp_core/images/productsGrey.png
    - packages/growerp_core/images/usersGrey.png
    - packages/growerp_core/images/chat.png
    - packages/growerp_core/images/dashBoard.png
    - packages/growerp_core/images/growerpAppstore.png
    - packages/growerp_core/images/myInfoGrey.png
    - packages/growerp_core/images/products.png
    - packages/growerp_core/images/users.png
    - packages/growerp_core/images/categoriesGrey.png
    - packages/growerp_core/images/companyGrey.png
    - packages/growerp_core/images/export.png
    - packages/growerp_core/images/growerp.jpg
    - packages/growerp_core/images/myInfo.png
    - packages/growerp_core/images/search.png
    - packages/growerp_core/images/chat.png
    - packages/growerp_core/images/chatGrey.png
    - packages/growerp_core/images/info.png
    - packages/growerp_core/images/infoGrey.png