name: growerp_catalog
description:  A catalog component for the Growerp ERP System containing, products, categories and assets
version: 0.8.0-dev.1
homepage: https://www.growerp.com
repository: https://github.com/growerp/growerp

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  growerp_core: ^0.8.0-dev.1
  #  path: ../growerp_core/
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  responsive_framework: ^0.2.0
  archive: ^3.3.0
  path_provider: ^2.0.11
  reorderables: ^0.5.1
  url_launcher: ^6.1.4
  flutter_colorpicker: ^1.0.3
  from_css_color: ^2.0.0
  markdown_widget: ^1.2.8
  freezed_annotation: ^2.0.3
  bloc_concurrency: ^0.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  image_picker: ^0.8.5
  global_configuration: ^2.0.0-nullsafety.0
  file_picker: ^5.0.1
  stream_transform: ^2.1.0
  json_annotation: ^4.7.0
  decimal: ^2.1.0
  fast_csv: ^0.1.44
  dropdown_search: ^4.0.1

dev_dependencies:
  freezed: ^2.0.3
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
