name: growerp_website
description:  A website component for the GrowERP system.
version: 0.5.0-dev.1
homepage: https://www.growerp.com
repository: https://github.com/growerp/growerp/tree/master/packages/growerp_website

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  growerp_core: # ^0.6.0-dev.6
    path: ../growerp_core/
  archive: ^3.3.0
  path_provider: ^2.0.11
  reorderables: ^0.5.1
  url_launcher: ^6.1.4
  flutter_colorpicker: ^1.0.3
  from_css_color: ^2.0.0
  markdown_widget: ^1.2.8

dev_dependencies:
  freezed: ^2.0.3
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
