name: growerp
version: 0.1.0-dev.8
description: GrowERP installation and tools
homepage: https://www.growerp.com
repository: https://github.com/growerp/growerp
platforms: 
  linux: null
  macos: null
  windows: null
executables: 
  growerp: null
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  dcli: ^1.36.2
  freezed_annotation: ^2.0.3
  json_annotation: ^4.8.0
  logger: ^1.3.0
  pub_api_client: ^2.4.0
  yaml_modify: ^1.0.1
dev_dependencies: 
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lint_hard: ^1.0.0
