name: utils
version: 0.0.1
description: A simple command-line application created by dcli
environment: 
  sdk: '>=2.16.0 <3.0.0'
dependencies: 
  dcli: 1.36.0
  freezed: ^2.3.2
  json_annotation: ^4.8.0
  logger: ^1.3.0
  pub_api_client: ^2.4.0
  yaml_modify: ^1.0.1
dev_dependencies: 
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  lint_hard: ^1.0.0
