name: hotel
version: 0.2.0+10
publish_to: none
environment: 
  sdk: '>=2.18.6 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  global_configuration: ^2.0.0-nullsafety.0
  meta: ^1.3.0
  shared_preferences: ^2.0.6
  animations: ^2.0.0
  growerp_website: 
    path: ../growerp_website/
  growerp_core: 
    path: ../growerp_core/
  growerp_order_accounting: 
    path: ../growerp_order_accounting/
  growerp_user_company: 
    path: ../growerp_user_company/
  growerp_catalog: 
    path: ../growerp_catalog/
  package_info_plus: ^3.1.2
  date_utils: ^0.2.0
  flutter_bloc: ^8.1.1
  intl: ^0.17.0
dependency_overrides:
  intl: ^0.18.0
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test: 
    sdk: flutter
  flutter_driver: 
    sdk: flutter
  utils: 
    path: ../utils
  mockito: ^5.0.3
  bloc_test: ^9.0.1
flutter_icons: 
  android: launcher_icon
  ios: true
  image_path: packages/growerp_core/images/hotel1.jpg
flutter: 
  uses-material-design: true
  assets: 
    - packages/growerp_core/images/single-bedGrey.png
    - packages/growerp_core/images/single-bed.png
    - packages/growerp_core/images/reservationGrey.png
    - packages/growerp_core/images/reservation.png
    - packages/growerp_core/images/check-in-outGrey.png
    - packages/growerp_core/images/check-in-out.png
    - assets/images/
    - assets/cfg/
    - assets/
    - ./
